"""ini657854

Revision ID: 3db6cf285d5a
Revises: cc0ef2da9fa7
Create Date: 2026-01-07 23:20:40.423178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3db6cf285d5a'
down_revision: Union[str, None] = 'cc0ef2da9fa7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('fingerprint', sa.String(), nullable=False))
    op.drop_index('ix_sessions_id', table_name='sessions')
    op.drop_column('sessions', 'device_id')
    op.drop_column('sessions', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.add_column('sessions', sa.Column('device_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.create_index('ix_sessions_id', 'sessions', ['id'], unique=False)
    op.drop_column('sessions', 'fingerprint')
    # ### end Alembic commands ###
